package com.jindo.core.mapper;

import com.jindo.core.model.User;
import com.jindo.core.model.UserExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_manhkm
     *
     * @mbg.generated Sat May 07 12:44:50 ICT 2022
     */
    long countByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_manhkm
     *
     * @mbg.generated Sat May 07 12:44:50 ICT 2022
     */
    int deleteByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_manhkm
     *
     * @mbg.generated Sat May 07 12:44:50 ICT 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_manhkm
     *
     * @mbg.generated Sat May 07 12:44:50 ICT 2022
     */
    int insert(User row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_manhkm
     *
     * @mbg.generated Sat May 07 12:44:50 ICT 2022
     */
    int insertSelective(User row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_manhkm
     *
     * @mbg.generated Sat May 07 12:44:50 ICT 2022
     */
    List<User> selectByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_manhkm
     *
     * @mbg.generated Sat May 07 12:44:50 ICT 2022
     */
    User selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_manhkm
     *
     * @mbg.generated Sat May 07 12:44:50 ICT 2022
     */
    int updateByExampleSelective(@Param("row") User row, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_manhkm
     *
     * @mbg.generated Sat May 07 12:44:50 ICT 2022
     */
    int updateByExample(@Param("row") User row, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_manhkm
     *
     * @mbg.generated Sat May 07 12:44:50 ICT 2022
     */
    int updateByPrimaryKeySelective(User row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_manhkm
     *
     * @mbg.generated Sat May 07 12:44:50 ICT 2022
     */
    int updateByPrimaryKey(User row);
    
    /**
     * Custom Query getAllUser()
     */
    List<Map<String, Object>> getAllUser(String userName);
    
    List<Map<String, Object>> getUserByUserNameAndId (Map<String, Object> param);
}